version: "2"

services:
  core:
    stdin_open: true
    tty: true
    container_name: core_container
    build: .
    command: bash -c "python manage.py migrate --noinput && gunicorn HtmlAnalyzer.wsgi:application --bind 0.0.0.0:8000"
    env_file:
      - .env
    volumes:
      - ./:/src
    expose:
      - 8000
    links:
      - db
    depends_on:
      - db

  db:
    container_name: db_container
    image: postgres:9.6.16
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=testing321
      - POSTGRES_DB=mydb
    volumes:
      - ./database:/var/lib/postgresql/data
  redis:
      image: redis:alpine
  celery:
    restart: always
    build:
      context: .
    command: celery -A server worker -l info

volumes:
  db_data: